annotations:
  artifacthub.io/changes: |-
    - kind: changed
      description: updated to 4.0.13
apiVersion: v2
appVersion: 4.0.13.2932
dependencies:
- name: common
  repository: https://bjw-s.github.io/helm-charts
  version: 1.5.1
description: sonarr - an internet PVR for Usenet and Torrents.
home: https://github.com/loeken/helm-charts
icon: https://d33wubrfki0l68.cloudfront.net/8c14075578b2f3d5c3c7acb0b73a911c1830aec4/96df1/images/avatar.png
maintainers:
- email: loeken@internetz.me
  name: loeken
name: sonarr
sources:
- https://github.com/loeken/helm-charts/tree/main/charts/sonarr
type: application
version: 4.0.13
