annotations:
  artifacthub.io/values-schema: values.schema.json
  artifacthub.io/changes: |-
    - kind: changed
      description: updated to 4.0.13
apiVersion: v2
appVersion: 4.0.16
dependencies:
- name: common
  repository: https://bjw-s-labs.github.io/helm-charts
  version: 4.6.2
description: sonarr - an internet PVR for Usenet and Torrents.
home: https://github.com/loeken/helm-charts
icon: https://gravatar.com/avatar/61f5b56ca85bc7e22f270e125c7e61ca?s=400
maintainers:
- email: loeken@internetz.me
  name: loeken
name: sonarr
sources:
- https://github.com/loeken/helm-charts/tree/main/charts/sonarr
type: application
version: 4.0.16
