annotations:
  artifacthub.io/values-schema: values.schema.json
  artifacthub.io/changes: |-
    - kind: changed
      description: updated to 10.10.6
apiVersion: v2
appVersion: 10.11.4
dependencies:
- name: common
  repository: https://bjw-s-labs.github.io/helm-charts
  version: 4.4.0
description: a helm chart to install jellyfin
home: https://github.com/loeken/helm-charts
icon: https://gravatar.com/avatar/61f5b56ca85bc7e22f270e125c7e61ca?s=400
maintainers:
- email: loeken@internetz.me
  name: loeken
name: jellyfin
sources:
- https://github.com/loeken/helm-charts/tree/main/charts/jellyfin
type: application
version: 10.11.4
