annotations:
  artifacthub.io/values-schema: values.schema.json
  artifacthub.io/changes: |-
    - kind: changed
      description: updated to 2.3.0
apiVersion: v2
appVersion: 3.1.0
dependencies:
- name: common
  repository: https://bjw-s-labs.github.io/helm-charts
  version: 4.6.2
description: a helm chart to install jellyseer
home: https://github.com/loeken/helm-charts
icon: https://gravatar.com/avatar/61f5b56ca85bc7e22f270e125c7e61ca?s=400
maintainers:
- email: loeken@internetz.me
  name: loeken
name: jellyseerr
sources:
- https://github.com/loeken/helm-charts/tree/main/charts/jellyseer
type: application
version: 3.1.0
