annotations:
  artifacthub.io/changes: |-
    - kind: changed
      description: updated to 5.15.1
apiVersion: v2
appVersion: version-5.15.1.9463
dependencies:
- name: common
  repository: https://bjw-s.github.io/helm-charts
  version: 1.5.1
description: a helm chart to install radarr
home: https://github.com/loeken/helm-charts
icon: https://d33wubrfki0l68.cloudfront.net/8c14075578b2f3d5c3c7acb0b73a911c1830aec4/96df1/images/avatar.png
maintainers:
- email: loeken@internetz.me
  name: loeken
name: radarr
sources:
- https://github.com/loeken/helm-charts/tree/main/charts/radarr
type: application
version: 5.15.1
