annotations:
  artifacthub.io/changes: |-
    - kind: changed
      description: updated to 1.23.16
apiVersion: v2
appVersion: 1.23.16
dependencies:
- name: common
  repository: https://bjw-s.github.io/helm-charts
  version: 3.7.1
description: uptime kuma - observability
  *arr software
home: https://github.com/loeken/helm-charts
icon: https://d33wubrfki0l68.cloudfront.net/8c14075578b2f3d5c3c7acb0b73a911c1830aec4/96df1/images/avatar.png
maintainers:
- email: loeken@internetz.me
  name: loeken
name: uptime-kuma
sources:
- https://github.com/loeken/helm-charts/tree/main/charts/uptime-kuma
type: application
version: 1.23.16
